services:
  app:
    build:
      args:
        user: laravel
        uid: 1000
        group: laravel
        gid: 1000
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ../:/var/www

  mysql:
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - docker-mysql:/var/lib/mysql

  nginx:
    image: nginx:stable-alpine
    working_dir: /var/www
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  redis:
    image: redis:5.0.4
    ports:
      - "6379:6379"

volumes:
  docker-mysql:
    driver: local
